# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Valensas
email: info@valensas.com
description: > # Valensas webpage
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://semihturan.xyz/valensas.com-demo" # the base hostname & protocol for your site
twitter_username: twitter.com/valensas
facebook_username:  facebook.com/valensas
host: 0.0.0.0
port: 4000
# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
