- title: Tekfen
  img: sample2.jpg
  description: Donec ullamcorper nulla non metus auctor fringilla.

- title: Veacon
  img: sample3.jpg
  description: Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.

- title: Akbank
  img: sample4.jpg
  description: Curabitur blandit tempus porttitor. Donec ullamcorper nulla non metus auctor fringilla.
